modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0-or-later"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="energybasedgear"
version="${file.jarVersion}"
displayName="Energy-Based Gear"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="logo.png"
credits="The Forge and FML guys"
authors="65_7a"
description='''
Energy-Based Gear is a content mod which adds weapons, tools and armour that makes use of the Forge Energy API.

Inspired by Redstone Arsenal by Team CoFH.
'''

[[dependencies.energybasedgear]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
